# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fnavi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fnavi
pod 'SwiftyJSON'
pod 'Alamofire'
  target 'FnaviTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FnaviUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
